AWSTemplateFormatVersion: "2010-09-09"
Description:
  ec2 base iam role

Resources:
  Ec2InstanceBaseRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub "ec2.${AWS::URLSuffix}"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: aws-infra-policy-ec2-base
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:Describe*"
                  - "ec2:CreateTags"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                  - "s3:GetObject"
                  - "s3:GetEncryptionConfiguration"
                  - "ssm:UpdateInstanceInformation"
                  - "ssmmessages:CreateControlChannel"
                  - "ssmmessages:CreateDataChannel"
                  - "ssmmessages:OpenControlChannel"
                  - "ssmmessages:OpenDataChannel"
                Resource: "*"

  Ec2InstanceBaseProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref Ec2InstanceBaseRole

## ------------------------------------------------------------#
## Output Parameters
## ------------------------------------------------------------#
Outputs:
  Ec2InstanceBaseRole:
    Value: !Ref Ec2InstanceBaseRole
    Export:
      Name: ec2-base-role

  Ec2InstanceBaseProfile:
    Value: !Ref Ec2InstanceBaseProfile
    Export:
      Name: ec2-base-profile